mongo:
    image: mongo
app:
    build: .
    command: node ./keystone.js
    volumes:
        # API stuff
        - ./app:/src/app
    ports:
        - "3000:3000"
    links:
        - mongo
    environment:
        PORT: 3000
        IP: 0.0.0.0
        MONGO_URI: mongodb://mongo/test
        COOKIE_SECRET: whatever
